### ISSUE TITLE
live examples 500

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [HelikarLab/ccNetViz#27] opened 2018-08-12 13:30 UTC
All examples in the README return 500

**Comment by gauravgrover95** [comment] 2018-08-13 05:40
@saskaale Can you take a look at this?

**Comment by gauravgrover95** [comment] 2018-12-09 09:54
Duplicate of #28

**Comment by saskaale** [comment] 2019-06-12 18:50
Fixed by deploying the new demo page and modifying links towards it

**Closed by saskaale** 2019-06-12 18:50 UTC
