### ISSUE TITLE
Examples mentioned in README not working

### ISSUE THREAD

**Issue by himanshuc3** [HelikarLab/ccNetViz#28] opened 2018-12-05 18:45 UTC

**Comment by gauravgrover95** [comment] 2018-12-07 18:10
Are you getting any error in browser's console? If yes, then can you please share it?

**Comment by gauravgrover95** [comment] 2018-12-07 18:23
This could be a possible duplicate of #27. The example was supposed to be saved as a file in the root directory of the fetched repository and should be called using a simple Http server which can be initiated from the command line using [Python](https://docs.python.org/2/library/simplehttpserver.html) or [PHP](http://php.net/manual/en/features.commandline.webserver.php) ?

Please let me know if you still face the issue after this and feel free to fix the documentation with a pull request. 🙂

**Comment by gauravgrover95** [comment] 2018-12-09 09:53
Yes. The live server is under maintainance.

Meanwhile, you can access the _Advanced Examples_ from the [repository](https://github.com/HelikarLab/ccNetViz/tree/master/examples) by running a [SimpleHttpServer](https://www.pythonforbeginners.com/modules-in-python/how-to-use-simplehttpserver/) and accessing examples folder in browser. Example:

In the root directory of the fetched repository run:
`python -m SimpleHTTPServer 8080`

Then in browser, Go to:
`http://localhost:8080/examples/complex.html`

Can you edit the documentation adding this alternative and generate a pull request for same?

Thanks.

**Comment by himanshuc3** [comment] 2018-12-11 09:37
I am going to close this issue as it is a duplicate.

**Closed** 2018-12-11 09:38 UTC
